# Generated by Django 5.0.7 on 2024-07-16 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ip',
            new_name='session_id',
        ),
    ]
