# Generated by Django 5.0.7 on 2024-07-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ip_client_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='window',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
