# Generated by Django 5.0.7 on 2024-07-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_window_height_window_width_window_x_window_y'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.window')),
            ],
        ),
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет солнца')),
                ('x', models.FloatField(verbose_name='X в рамках окна')),
                ('y', models.FloatField(verbose_name='Y в рамках окна')),
                ('radius', models.FloatField(verbose_name='Радиус в рамках окна')),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.system')),
            ],
        ),
    ]
